name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
        
    - name: Publish .NET Core Project
      run: |
        dotnet restore
        dotnet build --configuration Release
        dotnet publish -c Release -o release --nologo
    
    - name: Change base-tag in index.html
      run: |
        find release/wwwroot -name "index.html" -exec sed -i 's/<base href="\/"/<base href="\/andray-nkhatel.github.io\/"/g' {} +

    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
      
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot